# Generated by Django 4.2.30 on 2026-05-27 06:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ingestion', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scope', models.IntegerField(choices=[(1, 'Scope 1'), (2, 'Scope 2'), (3, 'Scope 3')])),
                ('category', models.CharField(choices=[('fuel', 'Fuel Combustion'), ('electricity', 'Electricity'), ('flight', 'Flight'), ('hotel', 'Hotel'), ('ground_transport', 'Ground Transport'), ('procurement', 'Procurement')], max_length=30)),
                ('subcategory', models.CharField(max_length=100)),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=18)),
                ('unit', models.CharField(max_length=30)),
                ('quantity_normalized', models.DecimalField(decimal_places=4, max_digits=18)),
                ('unit_normalized', models.CharField(max_length=30)),
                ('co2e_kg', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('co2e_tonnes', models.DecimalField(decimal_places=6, default=0, max_digits=18)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('facility_code', models.CharField(blank=True, max_length=50)),
                ('facility_name', models.CharField(blank=True, max_length=255)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('country', models.CharField(blank=True, max_length=2)),
                ('sap_document_number', models.CharField(blank=True, max_length=30)),
                ('sap_movement_type', models.CharField(blank=True, max_length=10)),
                ('sap_material_code', models.CharField(blank=True, max_length=40)),
                ('vendor_name', models.CharField(blank=True, max_length=255)),
                ('meter_id', models.CharField(blank=True, max_length=50)),
                ('account_number', models.CharField(blank=True, max_length=50)),
                ('tariff_code', models.CharField(blank=True, max_length=30)),
                ('traveler_id', models.CharField(blank=True, max_length=50)),
                ('origin', models.CharField(blank=True, max_length=10)),
                ('destination', models.CharField(blank=True, max_length=10)),
                ('distance_km', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('travel_class', models.CharField(blank=True, max_length=20)),
                ('review_status', models.CharField(choices=[('pending', 'Pending Review'), ('flagged', 'Flagged'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('reviewer_notes', models.TextField(blank=True)),
                ('is_locked', models.BooleanField(default=False)),
                ('is_manually_edited', models.BooleanField(default=False)),
                ('original_co2e_tonnes', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_records', to='ingestion.ingestionbatch')),
            ],
            options={
                'ordering': ['-period_start'],
            },
        ),
        migrations.CreateModel(
            name='EmissionFactor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=50)),
                ('subcategory', models.CharField(max_length=100)),
                ('unit_input', models.CharField(max_length=30)),
                ('factor_value', models.DecimalField(decimal_places=6, max_digits=12)),
                ('source', models.CharField(max_length=50)),
                ('version', models.CharField(max_length=20)),
                ('valid_from', models.DateField()),
                ('valid_to', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'unique_together': {('category', 'subcategory', 'unit_input', 'source', 'version')},
            },
        ),
        migrations.CreateModel(
            name='AnomalyFlag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('flag_type', models.CharField(choices=[('spike', 'Consumption Spike'), ('outlier', 'Statistical Outlier'), ('duplicate', 'Possible Duplicate'), ('unit_mismatch', 'Unit Mismatch'), ('missing_factor', 'Missing Emission Factor'), ('gap', 'Billing Period Gap')], max_length=30)),
                ('description', models.TextField()),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10)),
                ('is_resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('activity_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flags', to='emissions.activityrecord')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ActivityRecordEdit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('edited_at', models.DateTimeField(auto_now_add=True)),
                ('field_name', models.CharField(max_length=50)),
                ('old_value', models.TextField()),
                ('new_value', models.TextField()),
                ('reason', models.TextField(blank=True)),
                ('activity_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edits', to='emissions.activityrecord')),
                ('edited_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['edited_at'],
            },
        ),
        migrations.AddField(
            model_name='activityrecord',
            name='emission_factor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='emissions.emissionfactor'),
        ),
        migrations.AddField(
            model_name='activityrecord',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_records', to='core.organization'),
        ),
        migrations.AddField(
            model_name='activityrecord',
            name='raw_record',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_record', to='ingestion.rawrecord'),
        ),
        migrations.AddField(
            model_name='activityrecord',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='activityrecord',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_records', to='ingestion.datasource'),
        ),
        migrations.CreateModel(
            name='PlantMasterData',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('plant_code', models.CharField(max_length=10)),
                ('plant_name', models.CharField(max_length=255)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(blank=True, max_length=2)),
                ('region', models.CharField(blank=True, max_length=50)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plants', to='core.organization')),
            ],
            options={
                'unique_together': {('organization', 'plant_code')},
            },
        ),
        migrations.AddIndex(
            model_name='activityrecord',
            index=models.Index(fields=['organization', 'review_status'], name='emissions_a_organiz_217d40_idx'),
        ),
        migrations.AddIndex(
            model_name='activityrecord',
            index=models.Index(fields=['organization', 'scope', 'period_start'], name='emissions_a_organiz_3ca631_idx'),
        ),
        migrations.AddIndex(
            model_name='activityrecord',
            index=models.Index(fields=['batch'], name='emissions_a_batch_i_ebd650_idx'),
        ),
    ]
