# Generated by Django 4.2.30 on 2026-05-27 06:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataSource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('source_type', models.CharField(choices=[('SAP', 'SAP Flat File'), ('UTILITY', 'Utility CSV'), ('TRAVEL', 'Corporate Travel (Concur)')], max_length=20)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='core.organization')),
            ],
        ),
        migrations.CreateModel(
            name='IngestionBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('raw_file', models.FileField(blank=True, null=True, upload_to='batches/')),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('row_count', models.IntegerField(default=0)),
                ('parsed_count', models.IntegerField(default=0)),
                ('error_count', models.IntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('processing_log', models.JSONField(blank=True, default=list)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='ingestion.datasource')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='RawRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('row_number', models.IntegerField()),
                ('raw_data', models.JSONField()),
                ('parse_status', models.CharField(choices=[('parsed', 'Parsed'), ('error', 'Error'), ('skipped', 'Skipped')], default='parsed', max_length=10)),
                ('parse_errors', models.JSONField(blank=True, default=list)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raw_records', to='ingestion.ingestionbatch')),
            ],
            options={
                'ordering': ['batch', 'row_number'],
            },
        ),
    ]
